Document: rcssserver3d-spl
Title: Debian rcssserver3d-spl Manual
Author: <insert document author here>
Abstract: This manual describes what rcssserver3d-spl is
 and how it can be used to
 manage online manuals on Debian systems.

Format: debiandoc-sgml
Files: /usr/share/doc/rcssserver3d-spl/rcssserver3d-spl.sgml.gz

Format: postscript
Files: /usr/share/doc/rcssserver3d-spl/rcssserver3d-spl.ps.gz

Format: text
Files: /usr/share/doc/rcssserver3d-spl/rcssserver3d-spl.text.gz

Format: HTML
Index: /usr/share/doc/rcssserver3d-spl/html/index.html
Files: /usr/share/doc/rcssserver3d-spl/html/*.html
